### ISSUE TITLE
Editable Wecommerce Layout and placment

### ISSUE THREAD

**Issue by akargurita** [andersnoren/hideo#3]
Can the section and pattern of WooCommerce be edited to support customization similar to the patterns in the Hideo Theme?

I'm facing challenges adapting the theme style to WooCommerce's default patterns.

**Comment by andersnoren** [comment]
@akargurita Hideo isn't built for or tested with WooCommerce, so it's likely you'll run into some design niggles when using the two together. 

That said, I think any customization questions for WooCommerce specific blocks/patterns/template parts would be better directed to the WooCommerce support forums or GitHub repository.

**Comment by akargurita** [comment]
My bad, thanks for helping out with Hideo. I've been a fan of your WP themes since Beaumont. If you don't mind answering this, among all your themes, which one has the most WooCommerce patterns?

**Comment by andersnoren** [comment]
Of course! None of my modern themes (block themes) are built specifically with WooCommerce in mind, so none of them have WooCommerce patterns included.
