### ISSUE TITLE
Images are thumbnails

### ISSUE THREAD

**Issue by werdinand** [andersnoren/hideo#4]
I tried to switch from Fukasawa to Hideo but in Hideo all the images are 88x88 thumbnails and therefore totally blurry. Is there a simple fix for that?

**Comment by andersnoren** [comment]
@werdinand It sounds like you need to run the "Regenerate Thumbnails" plugin once you've activated Hideo, so the images in your media library are updated to use the image sizes set in the theme.

**Comment by werdinand** [comment]
Tried that but still all the images are 88x88 thumbnails. 
There is similar problem in Koji but with Koji on the front page images are as they should, and in the post page the image is square over sized thumbnail.

**Comment by andersnoren** [comment]
@werdinand Koji doesn't use the `post-thumbnail` image size on the front page, so that's at least consistent. It could be that a plugin is overriding the post thumbnail size set by your active theme.

Can you post a link to the site?

**Comment by werdinand** [comment]
https://www.phogulum.com/

**Comment by andersnoren** [comment]
I'm getting full resolution images on the single posts:

<img width="1021" alt="image" src="https://github.com/andersnoren/hideo/assets/8181091/3103a6ce-69c8-4d99-8dfe-d661487fd096">

**Comment by werdinand** [comment]
That's because it's Fukasawa and it's working fine. Sorry, I didn't know that you wanted to see the blog in broken state (and I didn't want to leave it broken for a long time). Now I switched the theme to Koji and the same image should be blurry as hell.

**Comment by werdinand** [comment]
At the moment it's more like this:
![koji-blur](https://github.com/andersnoren/hideo/assets/163354226/60d24f85-59b7-4e5c-970c-40287d173679)

**Comment by andersnoren** [comment]
That's the post-thumbnail image size being used, but set to 88x88px by some previous theme. 

If you activate and run the Regenerate Thumbnails plugin while Koji is active (at Tools → Regenerate Thumbnails), WordPress will regenerate new versions of the images, with the post thumbnail size specified by Koji.

**Comment by werdinand** [comment]
Regenerate Thumbnails plugin didn't help. I tried it several times with Hideo and with Koji but nothing changed. Finally I tried some other regenerating plugin with 'force' option and that did the trick. Thank you!
